### ISSUE TITLE
Segmentation fault on Ubuntu 16.10

### ISSUE THREAD

**Issue by sumire-uematsu** [mynlp/lilfes#1]
Related issue https://github.com/mynlp/enju/issues/1
The issue is reported to enju, but it seems to be a problem of lifles.

I reproduced the error on ubuntu 16.10 installed on VM.
After `make` finished successfully, running 'lilfes' gives segmentation faults.
Both master and develop branches caused the error. 
The same codes run normally on ubuntu 15 LTS

**Comment by kkos** [comment]
I made tiny fix on develop branch.
I found \_\_GLIBCXX\_\_ is not defined for some cases. (I don't know the reason.)
I have removed \_\_GLIBCXX\_\_ check from hashdef.h.
It passed "make check".

**Comment by sumire-uematsu** [comment]
Thank you! I checked the develop branch passes "make check" and simple tests on Ubuntu 15 LTS and 16.10.
The branch should be merged to the master.
